version: "3.9"

services:

  db:
    image: postgres:16
    container_name: weather_db
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  logger:
    build: ./app
    container_name: weather_logger
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: